In [1]:
print("Om Varaduntaaya Namah")

Om Varaduntaaya Namah


### Array Manipulation 
* Numpy Arithmetic Operations
* Slicing Arrays
* iterating over arrays 
* Array Concatenation
* Splitting Arrays 
* Numpy histogram usig matplotlib 
* Other useful functions in Numpy  
* Broadcasting

In [2]:
import numpy as np

In [4]:
print(np.__version__)

1.16.2


# Array of integers, floats and complex numbers

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1 2 3]
 [3 4 5]]
[[1.1 2.  3. ]
 [3.  4.  5. ]]
[[1.+0.j 2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j 5.+0.j]]


In [4]:
a1 = np.array([2,3,4])
type(a1)

numpy.ndarray

In [5]:
a1.dtype

dtype('int64')

In [6]:
a2 = np.array([2,3,4],dtype='float64')
type(a2)
a2.dtype

dtype('float64')

In [7]:
a2.shape  # shape => (rows, columns)

(3,)

In [56]:
a2.ndim

1

In [19]:
a1

array([2, 3, 4])

# Slicing or subseting the data

In [18]:
a1[a1 > 1]

array([2, 3, 4])

In [30]:
a1 = np.array([ [2,3,1],[6,5,4] ])
a1

array([[2, 3, 1],
       [6, 5, 4]])

In [33]:
a2 = np.where(a1<4)
a2

(array([0, 0, 0]), array([0, 1, 2]))

In [37]:
a1[a2]

array([2, 3, 1])

In [28]:
a2 =np.where(a1 < 2)
a2


(array([], dtype=int64),)

In [10]:
l = [2,4,6]

In [11]:
a1 + l

array([ 4,  7, 10])

In [7]:
a1.argmax()

2

In [8]:
a1

array([2, 3, 4])

In [5]:
# a1{start:end-1}
a1[0:3]

array([2, 3, 4])

In [6]:
a1[-1]

4

In [7]:
a = np.array([ [8,7,6],[3,2,1],[2,3,9]])
a

array([[8, 7, 6],
       [3, 2, 1],
       [2, 3, 9]])

In [8]:
a.shape

(3, 3)

In [9]:
a[1,2]

1

In [11]:
a[0:2,1]

array([7, 2])

In [12]:
a[:,1:3]

array([[7, 6],
       [2, 1],
       [3, 9]])

In [14]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [16]:
list(range(1,6))

[1, 2, 3, 4, 5]

In [17]:
a2 = np.arange(6).reshape(3,2)
a2

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
a3 = np.arange(6,12).reshape(3,2)
a3

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
a3 + 2

array([[ 8,  9],
       [10, 11],
       [12, 13]])

# Multidimensional arrays

In [42]:
a1 = np.array([[2,4,6,8],[2,1,3,4],[4,1,2,1]])
a1=a1.reshape(3,2,2)  # here the a1 holds an address for two 2x3 arrays as [0,1]  a1[0] points to [2,4,6,8,2,1] & so on
a1  # a1[0|1|2]

array([[[2, 4],
        [6, 8]],

       [[2, 1],
        [3, 4]],

       [[4, 1],
        [2, 1]]])

In [44]:
a1.shape

(3, 2, 2)

In [47]:
a1[0][0][0]

2

In [46]:
a1*2

array([[[ 4,  8, 12],
        [16,  4,  2]],

       [[ 6,  8,  8],
        [ 2,  4,  2]]])

In [48]:
a1 = np.array([[2,4,6,8],[2,1,3,4],[4,1,2,1],[2,7,6,5]])
a1=a1.reshape(4,2,2)  # here the a1 holds an address for two 2x3 arrays as [0,1]  a1[0] points to [2,4,6,8,2,1] & so on
a1

array([[[2, 4],
        [6, 8]],

       [[2, 1],
        [3, 4]],

       [[4, 1],
        [2, 1]],

       [[2, 7],
        [6, 5]]])

In [49]:
a1[1]

array([[2, 1],
       [3, 4]])

In [50]:
a1[2]

array([[4, 1],
       [2, 1]])

In [51]:
a1.ndim

3

## Numpy Arithmetic Operations

In [15]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
b = np.array([10,11,12])
b

array([10, 11, 12])

In [17]:
a+b
np.add(a,b)

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20]])

## iterating over an array

In [16]:
for i in a:
    print(i + 10)

[10 11 12]
[13 14 15]
[16 17 18]


In [19]:
for i in np.nditer(a):
    print(i)
i

0
1
2
3
4
5
6
7
8


array(8)

In [20]:
l = [9,7,10,12]
l * 2

[9, 7, 10, 12, 9, 7, 10, 12]

# splitting array

In [21]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.split(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [21]:
np.split(a,[1,2])

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

# Other useful functions  in array

In [22]:
a = np.linspace(1,3,5)  # it genertes 5 values from 1 to 3 evenly spaced
a

array([1. , 1.5, 2. , 2.5, 3. ])

In [27]:
a

array([1. , 1.5, 2. , 2.5, 3. ])

In [23]:
a = np.array([[2,4,6],[3,2,1]])
a

array([[2, 4, 6],
       [3, 2, 1]])

In [24]:
a.ravel()

array([2, 4, 6, 3, 2, 1])

In [25]:
#a.rollaxis(a,1,2)
a = np.array([2,4,6,8])
a.swapaxes(a,2)

TypeError: only size-1 arrays can be converted to Python scalars

In [22]:
a2 + a3

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [23]:
a2.shape

(3, 2)

In [25]:
a3.shape

(3, 2)

In [26]:
a3.flatten()

array([ 6,  7,  8,  9, 10, 11])

In [27]:
a3

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [28]:
a3.flatten(order='F')

array([ 6,  8, 10,  7,  9, 11])

In [29]:
a = np.array([ [[1,2,3],[3,4,5]],[[6,7,8],[9,10,11]] ])
a

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [30]:
a.shape

(2, 2, 3)

In [39]:
a.flatten(order='C') # C is a row wise operation , F is the colummn wise operation, K is the order in which the
# elements occur in memory

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a.flatten(order='F')

array([ 1,  6,  3,  9,  2,  7,  4, 10,  3,  8,  5, 11])

In [38]:
a.flatten(order='K')

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Broadcasting

In [42]:
a = np.arange(3)
b = np.array([2,4,6])
print(a)
print(b)

[0 1 2]
[2 4 6]


In [43]:
a

array([0, 1, 2])

In [44]:
a + 1

array([1, 2, 3])

In [45]:
a + b

array([2, 5, 8])

In [46]:
a = np.arange(6).reshape(2,3)
b = np.array([0,1,2])

In [ ]:
a + b

In [47]:
a.shape

(2, 3)

In [48]:
b.shape

(3,)

In [49]:
b

array([0, 1, 2])

In [50]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [51]:
a + b

array([[0, 2, 4],
       [3, 5, 7]])

In [53]:
a = np.array([0,3]).reshape(2,1)
b=np.array([0,1]).reshape(2,1)
print(a)
print(b)

[[0]
 [3]]
[[0]
 [1]]


In [54]:
a+b

array([[0],
       [4]])

In [62]:
a = np.array([0,3]).reshape(2,1)
print(a)
b = np.array([0,1,2])
print(b)


[[0]
 [3]]
[0 1 2]


In [57]:
a.shape

(2, 1)

In [58]:
b.shape

(3,)

In [61]:
a+b

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
a = np.array([0,3]).reshape(1,2)
print(a)
b = np.array([0,1,2,4])
print(b)
a+b

[[0 3]]
[0 1 2 4]


ValueError: operands could not be broadcast together with shapes (1,2) (4,) 

In [65]:
a.shape

(1, 2)

In [66]:
b.shape

(4,)

In [67]:
a

array([[0, 3]])

In [69]:
b

array([0, 1, 2, 4])

In [70]:
n1 = np.ones([2,3])

n1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.full((4,4),99)

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

# Multiplication of Matrices

In [49]:
import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


In [50]:
B

array([[ 1,  1],
       [ 2,  1],
       [ 3, -3]])

In [51]:
C

array([[ 36, -12],
       [ -1,   2]])

In [52]:
A

array([[ 3,  6,  7],
       [ 5, -3,  0]])

In [58]:
m = np.mat([[2,3,4],[4,6,8]])
m

matrix([[2, 3, 4],
        [4, 6, 8]])

In [59]:
m.shape

(2, 3)

In [54]:
m  * 2

matrix([[ 4,  6,  8],
        [ 8, 12, 16]])

In [62]:
n = np.mat([[2,3,4],[4,6,8],[1,4,1]])
n

matrix([[2, 3, 4],
        [4, 6, 8],
        [1, 4, 1]])

In [63]:
n.shape

(3, 3)

In [64]:
m.dot(n)

matrix([[20, 40, 36],
        [40, 80, 72]])

## Assignment Solutions

In [27]:

l=[]
for i in range(2000, 3201):
    if (i%7==0) and (i%5!=0):
        l.append(str(i))

print( ','.join(l))


2002,2009,2016,2023,2037,2044,2051,2058,2072,2079,2086,2093,2107,2114,2121,2128,2142,2149,2156,2163,2177,2184,2191,2198,2212,2219,2226,2233,2247,2254,2261,2268,2282,2289,2296,2303,2317,2324,2331,2338,2352,2359,2366,2373,2387,2394,2401,2408,2422,2429,2436,2443,2457,2464,2471,2478,2492,2499,2506,2513,2527,2534,2541,2548,2562,2569,2576,2583,2597,2604,2611,2618,2632,2639,2646,2653,2667,2674,2681,2688,2702,2709,2716,2723,2737,2744,2751,2758,2772,2779,2786,2793,2807,2814,2821,2828,2842,2849,2856,2863,2877,2884,2891,2898,2912,2919,2926,2933,2947,2954,2961,2968,2982,2989,2996,3003,3017,3024,3031,3038,3052,3059,3066,3073,3087,3094,3101,3108,3122,3129,3136,3143,3157,3164,3171,3178,3192,3199


In [30]:
items=[x for x in input().split(',')]
items.sort()
print (','.join(items))


without,hello,bag,world
bag,hello,without,world


In [32]:
lines = []
while True:
    s = input()
    if s:
        lines.append(s.upper())
    else:
        break;

for sentence in lines:
    print (sentence)


Hello world
PRACTICE MAKES PERFECT
Hello world
PRACTICE MAKES PERFECT
PRACTICE MAKES PERFECT
Hellow  World


KeyboardInterrupt: 

In [34]:
value = []
items=[x for x in input().split(',')]
for p in items:
    intp = int(p, 2)
    if not intp%5:
        value.append(p)

print (','.join(value))


0100,0011,1010,1001
1010


In [37]:
#Solution:
values = []
for i in range(1000, 3001):
    s = str(i)
    if (int(s[0])%2==0) and (int(s[1])%2==0) and (int(s[2])%2==0) and (int(s[3])%2==0):
        values.append(s)
print (",".join(values))


2000,2002,2004,2006,2008,2020,2022,2024,2026,2028,2040,2042,2044,2046,2048,2060,2062,2064,2066,2068,2080,2082,2084,2086,2088,2200,2202,2204,2206,2208,2220,2222,2224,2226,2228,2240,2242,2244,2246,2248,2260,2262,2264,2266,2268,2280,2282,2284,2286,2288,2400,2402,2404,2406,2408,2420,2422,2424,2426,2428,2440,2442,2444,2446,2448,2460,2462,2464,2466,2468,2480,2482,2484,2486,2488,2600,2602,2604,2606,2608,2620,2622,2624,2626,2628,2640,2642,2644,2646,2648,2660,2662,2664,2666,2668,2680,2682,2684,2686,2688,2800,2802,2804,2806,2808,2820,2822,2824,2826,2828,2840,2842,2844,2846,2848,2860,2862,2864,2866,2868,2880,2882,2884,2886,2888


** Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers.
** Suppose the following input is supplied to the program:


In [44]:
values = input()
numbers = [str(int(x) **2) for x in values.split(",") if int(x)%2!=0]
print (",".join(numbers))
#print(numbers)

1,2,3,4,5,6,7,8,9
1,9,25,49,81


In [46]:
x = lambda x,y: (x+y)/2
x(6,4)

5.0

In [47]:
s1 = lambda s: list(set(s))
s1('ababcde')

['e', 'd', 'a', 'c', 'b']

In [48]:
from functools import reduce

def Average(l): 
    avg = reduce(lambda x, y: x + y, l) / len(l)
    return avg
  
my_list = [2,4,6,8,10] 
average = Average(my_list) 
  
print ("Average of my_list is", average)

Average of my_list is 6.0
