In [2]:
import numpy as np

In [4]:
m = np.mat([ [2,3,1],[4,5,6],[6,3,2] ],dtype = "int32")
m

matrix([[2, 3, 1],
        [4, 5, 6],
        [6, 3, 2]], dtype=int32)

In [6]:
m.dtype

dtype('int32')

In [7]:
y = np.mat( [[5,8,1],[6,7,2],[4,5,9]])
y

matrix([[5, 8, 1],
        [6, 7, 2],
        [4, 5, 9]])

In [9]:
m+y

matrix([[ 7, 11,  2],
        [10, 12,  8],
        [10,  8, 11]])

In [14]:
len(m)

3

In [19]:
list(range(len(m[0])))

[0]

In [22]:
res = np.mat([[0,0,0],[0,0,0],[0,0,0]])
res.shape

(3, 3)

In [24]:
# iterate through rows
for i in range(len(m)):
    # iterate through columns
    for j in range(len(m[0])):
        res[i][j] = m[i][j] + y[i][j]
for i in res:
    print(i)

[[ 7 11  2]]
[[10 12  8]]
[[10  8 11]]


In [10]:
m*y # matrix multiplication

matrix([[32, 42, 17],
        [74, 97, 68],
        [56, 79, 30]])

In [11]:
m.dot(y) # matrix multiplication

matrix([[32, 42, 17],
        [74, 97, 68],
        [56, 79, 30]])

In [12]:
m

matrix([[2, 3, 1],
        [4, 5, 6],
        [6, 3, 2]], dtype=int32)

In [13]:
y

matrix([[5, 8, 1],
        [6, 7, 2],
        [4, 5, 9]])

In [ ]:
# m x n *  n x p => m * p

## Matrix Transpose

In [25]:
m.T

matrix([[2, 4, 6],
        [3, 5, 3],
        [1, 6, 2]], dtype=int32)

In [26]:
m

matrix([[2, 3, 1],
        [4, 5, 6],
        [6, 3, 2]], dtype=int32)

## How to change the value of matrix diagonal

In [27]:
m

matrix([[2, 3, 1],
        [4, 5, 6],
        [6, 3, 2]], dtype=int32)

In [29]:
np.fill_diagonal(m,1)

In [30]:
m

matrix([[1, 3, 1],
        [4, 1, 6],
        [6, 3, 1]], dtype=int32)

## how to add a number to the diagonal elements of a matrix

In [32]:
np.fill_diagonal(m,m.diagonal()+10)


In [33]:
m

matrix([[11,  3,  1],
        [ 4, 11,  6],
        [ 6,  3, 11]], dtype=int32)

## element wise multiplication 

In [34]:
m

matrix([[11,  3,  1],
        [ 4, 11,  6],
        [ 6,  3, 11]], dtype=int32)

In [36]:
y

matrix([[5, 8, 1],
        [6, 7, 2],
        [4, 5, 9]])

In [38]:
np.multiply(m,y)

matrix([[55, 24,  1],
        [24, 77, 12],
        [24, 15, 99]])

In [39]:
m.shape

(3, 3)

In [41]:
z = np.mat([ [1,2,3],[2,4,6]])
z.shape

(2, 3)

In [44]:
m*z

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [45]:
z*m  # multiplication of two m and z is defined only if the number of columns in m is equal to the number of rows m 

matrix([[37, 34, 46],
        [74, 68, 92]])

In [46]:
z.shape

(2, 3)

In [47]:
m.shape

(3, 3)